# Generated by Django 2.0.2 on 2018-03-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_auto_20180303_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billtransation',
            name='state',
        ),
        migrations.AddField(
            model_name='abstractbasetransation',
            name='state',
            field=models.CharField(choices=[('UP', 'Unpaid'), ('SU', 'Suspend-Unpaid'), ('PD', 'Paid'), ('SP', 'Suspend-Paid'), ('DC', 'Decliend')], default='UP', max_length=2),
        ),
    ]
