# Generated by Django 2.0.2 on 2018-03-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_auto_20180304_0513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clearing',
            name='flag_bill',
        ),
        migrations.RemoveField(
            model_name='clearingtransation',
            name='abstractbasetransation_ptr',
        ),
        migrations.RemoveField(
            model_name='clearingtransation',
            name='clearing',
        ),
        migrations.AlterField(
            model_name='bill',
            name='state',
            field=models.CharField(choices=[('PD', 'Pending'), ('PC', 'Processing'), ('FN', 'Finished')], default='PC', max_length=2),
        ),
        migrations.DeleteModel(
            name='Clearing',
        ),
        migrations.DeleteModel(
            name='ClearingTransation',
        ),
    ]
