# Generated by Django 2.0.2 on 2018-03-16 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bills', '0004_auto_20180314_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('msg', models.CharField(max_length=1024)),
                ('state', models.CharField(choices=[('PD', 'Pending'), ('WT', 'Waitting'), ('PC', 'Processing'), ('VR', 'Verifying'), ('FN', 'Finished')], default='PD', max_length=2)),
                ('initiate_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tr_flag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bills.AbstractBaseTransation')),
            ],
        ),
        migrations.CreateModel(
            name='SettleTransation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('UP', 'Unpaid'), ('PD', 'Paid-Verifying'), ('VD', 'Verified')], default='UP', max_length=2)),
                ('service_fee', models.DecimalField(decimal_places=2, max_digits=7)),
                ('penalty', models.DecimalField(decimal_places=2, max_digits=7)),
                ('reset_tr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.AbstractBaseTransation')),
                ('settle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.Settle')),
            ],
        ),
    ]
