# Generated by Django 2.0.2 on 2018-03-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0006_auto_20180318_0848'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SettleTransation',
            new_name='SettleTransaction',
        ),
        migrations.AlterField(
            model_name='settle',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
